### ISSUE TITLE
Week02-01

### ISSUE THREAD

**Issue by zhamri** [zhamri/STIW3054#1]
You are required to create a simple program for counting thread. It will count to 10500, pausing five seconds between each number, and displaying a string every 50 numbers.

**Comment by syeel** [comment]
public class CountTo10500 extends Thread{

   int counter =0, target=51;
   
   public static void main(String[] args){
      new Thread(new CountTo10500()).start();
   }
   
   public void printString(){
      System.out.println("Lalala, this is a string.");
   }
  
   @Override
   public void run() {
      try {
         for (int x = 0; x <= 10500; x++) {
            System.out.println(x);
            sleep(100);
            counter++;
                
            if (counter == target){
               printString();
               target += 50; 
            }  
         }
      }catch (Exception e){
         e.printStackTrace();
      }
   }
}

**Comment by Jiayin328** [comment]
public class MyThread extends Thread {

    public static void main(String[] args) {
        new Thread(new MyThread()).start();
    }

    @Override
    public void run() {
        try {
            for (int x = 1; x <= 10500; x++) {
                System.out.println(x);
                sleep(5000);
                if (x%50==0){
                    System.out.println("Hello World");
                }
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by DonLeeHoi** [comment]
public class CountThread extends Thread{

	//Count Thread to 10500
	//Pause 5 seconds between numbers
	//Display String every 50 numbers

	public static void main(String[] args) {
		
		 new Thread(new CountThread()).start();
	}
	
	@Override
    public void run() {
        try {
            for (int x = 0; x < 10500; x++) {
                System.out.println(x);
               if((x % 50 == 0)&&(x != 0)){
            	System.out.println("--Check--"); 
               }
                sleep(5000);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by MarJr** [comment]
public class CountingThread extends Thread {

    int count = 0, limit = 51;

    public static void main(String[] args) {
        new Thread(new CountingThread()).start();
    }

    @Override
    public void run() {
        try {
            for (int i = 0; i <= 10500; i++) {
                System.out.println(i);
                sleep(5000);
                count++;

                if (count == limit) {
                    int limit1 = limit - 1;
                    System.out.println("\nDah sampai " + limit1 + " daaa\n");
                    limit += 50;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by TeeMeiYit** [comment]
public class TreadCount extends Thread {

    public static void main(String[] args) {
        new Thread(new TreadCount()).start();
    }

    @Override
    public void run() {
        try {
            for (int x = 0; x < 10500; x++) {
                System.out.println(x);
                sleep(5000);
                    if(x % 50 == 0 && x != 0){
                        System.out.println("Reached 50 numbers.");
                    }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by chinonn** [comment]
package WeakOne;

	public class WeakOne extends Thread {

	    public static void main(String[] args) {
	        new Thread(new WeakOne()).start();
	    }

	    @Override
	    public void run() {
	        try {
	            for (int x = 1; x <= 10500; x++) {
	                System.out.println(x);
	                sleep(5000);
	                if (x%50==0){
	                    System.out.println("This is a String");
	                }
	            }
	            
	        } catch (Exception e) {
	            e.printStackTrace();
	        }
	    }
	}

**Comment by chinonn** [comment]
package WeakOne;

	public class WeakOne extends Thread {
		private String message="Fifty Level Reached";

	    public static void main(String[] args) {
	        new Thread(new WeakOne()).start();
	    }
	    
	    public void DisplayMessage(String message){
	    	this.message = message;
	    }

	    @Override
	    public void run() {
	        try {
	            for (int x = 1; x <= 10500; x++) {
	                System.out.println(x);
	                sleep(5000);
	                if (x%50==0){
	                    System.out.println(message);
	                }
	            }
	            
	        } catch (Exception e) {
	            e.printStackTrace();
	        }
	    }
	}

**Comment by bad96** [comment]
package test1;

public class Test1 extends Thread {

    public static void main(String[] args) {
        new Thread(new Test1()).start();
    }

    public void run() {
        try {
            for (int x = 0; x <10500; x++) {
                System.out.println(x);
                sleep(50);
                if(x%50==0)
                System.out.println("---Hello---");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by LeeCheryn** [comment]
public class CountThread extends Thread {
    
    @Override
    public void run(){
        try{
            for(int i=0; i<=10500; i++){
                if(i%50==0 && i!=0)
                    System.out.println("Hello");
            System.out.println(i);
            sleep(5000);
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }
    
    public static void main(String args[]){
        new Thread(new CountThread()).start();
        
    }
}

**Comment by zaemie** [comment]
public class MySleep extends Thread {

    public static void main(String[] args) {
        new Thread(new MySleep()).start();
    }

    @Override
    public void run() {
        try {
            for (int x = 0; x < 10500; x++) {
                System.out.println(x);
                sleep(5000);
                
                if((x%50==0)&&(x!=0)){
                    System.out.println("String");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by wzul** [comment]
I am thinking about having two Thread which every Thread responsible for:
1. For **incrementing** the **numbers**.
2. For **checking the incrementing numbers** and **output** something.

Tried so many ways. Cannot get it to work. Here's my code:

```java
public class Issue01 extends Thread {

    public static int count = 0;
    public static int sleepSeconds = 5000;
    public static boolean completed = false;
    public static boolean waitNext = false;
    public static String outputText = "----------AAAA-----------";

    public static void main(String[] args) {
        
        new Thread(new CheckCounting()).start();
        new Thread(new Issue01()).start();
    }

    @Override
    public void run() {
        try {
            for (; count <= 10500; count++) {
                waitNext = false;
                System.out.println(count);
                sleep(sleepSeconds);
            }
            completed = true;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

class CheckCounting extends Thread {

    @Override
    public void run() {
        while (!Issue01.completed) {
            if ((Issue01.count % 50 == 0) && (!Issue01.waitNext) && (Issue01.count != 0)) {
                System.out.println(Issue01.outputText);
                Issue01.waitNext = true;
            }

        }
    }
}
```

**Comment by zhamri** [comment]
Problem solved. Thanks everyone.

@wzul .... you should think as simple as you can :)

**Comment by wzul** [comment]
https://github.com/adam-p/markdown-here/wiki/Markdown-Here-Cheatsheet
