### ISSUE TITLE
Week02-02

### ISSUE THREAD

**Issue by zhamri** [zhamri/STIW3054#2]
You are required to create a simple program by using **TWO (2)** threads. The first thread will display integer numbers 1 to 10 and the second thread will display ‘A’ character ten times. The ‘A’ characters will be displayed after number 5 and number 6,7,8,9,10 will be displayed after all As have been printed.

**Example of the output is as follows:**

1 2 3 4 5 AAAAAAAAAA 6 7 8 9 10

**Comment by wzul** [comment]
```java
package javaapplication5;

public class JavaApplication5 extends Thread {

    public static int nombor = 1;

    public static void main(String[] args) {
        new Thread(new JavaApplication5()).start();
        new Thread(new PrintA()).start();
    }

    @Override
    public void run() {
        try {
            for (; JavaApplication5.nombor <= 10; JavaApplication5.nombor++) {
                if (JavaApplication5.nombor == 6) {
                    sleep(1000);
                }
                System.out.print(JavaApplication5.nombor+ " ");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

class PrintA extends Thread {

    @Override
    public void run() {
        if (JavaApplication5.nombor == 6) {
            System.out.print("AAAAAAAAAA ");
        }
    }
}

```

**Comment by zhamri** [comment]
"AAAAAAAAAA" .... I consider this as one string .....not ‘A’ character ten times ....

**Comment by wzul** [comment]
Using char and repeat it 10 times

```java
    @Override
    public void run() {
        while (true) {
            if (JavaApplication5.nombor == 6) {
                for (int i = 0; i < 10; i++) {
                    System.out.print(JavaApplication5.huruf);
                }
                System.out.print(" ");
                break;
            }
        }
    }
```

**Comment by LeeCheryn** [comment]
public class TwoThreads extends Thread {
  
    static TwoThreads t1 = new TwoThreads(){
        public void run(){
            try{
                for(int i=1; i<=10; i++){
                    System.out.print(i+" ");
                    if(i==5){
                        t2.start();
                    }
                    sleep(1000);
                }
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    };
    
    static TwoThreads t2 = new TwoThreads(){
        public void run(){
            try{
                for(int j=0; j<10; j++)
                    System.out.print("A"); 
                
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    };
    
    public static void main(String[] args) {
        t1.start();
    }
}

**Comment by TeeMeiYit** [comment]
package MyThreadTwo;

public class MyThreadTwo extends Thread {

    public static void main(String[] args) {
        MyThreadTwo t1 = new MyThreadTwo();
        MyThreadTwo t2 = new MyThreadTwo();
        
        for (int x = 1; x < 11; x++) {
            System.out.print(x + " ");
                
                if(x==5){
                    for(int i = 0; i < 10; i++){
                    System.out.print("A");
                    } 
                }
        }
    }
}

**Comment by ongjingwen** [comment]
public class TwoThread {

    public static void main(String[] args) {
       
        Thread t1 = new Thread();
        Thread t2 = new Thread();
        
        
        try{
            for (int x = 1; x < 11; x++) {
                System.out.print(x + " "); 
                 if (x==5){
                    for(int i=0; i<10; i++)
                    System.out.print("A"+""); 
                 }     
            }
    }
      catch(Exception e){
       e.printStackTrace();
        }
   }}

**Comment by shiausee** [comment]
package twothreadw2_02;

public class TwoThreadw2_02 extends Thread {
    public static void main(String[] args) {
       
       TwoThreadw2_02 t1 = new TwoThreadw2_02();
       t1.run();
      
    }
    
    public void run(){
    try{
        for(int i=1;i<11;i++){
            System.out.print(i+" ");
            if(i==5){
                TwoThreadw2_02 t2 = new TwoThreadw2_02();
                t2.stringAL();
            }
        }
    }catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void stringAL(){
        for(int x=1; x<11 ;x++ ){
            System.out.print("W ");
        }
    }
    }

**Comment by Tamilarasi95** [comment]
public class TwoThread extends Thread {

public static void main(String[] args) {
   
    TwoThread t1 = new TwoThread();
    TwoThread t2 = new TwoThread();
    
   
    try{
        for (int i = 1; i <= 10; i++) {
            System.out.print(i + " ");
            
             if (i==5){
                for(int j=0; j<10; j++)
                System.out.print("A"); 
             }     
        }
}
     catch(Exception e){
      e.printStackTrace();
     }
 }
    
 }

**Comment by h4nn4** [comment]
public class CountThread123 extends Thread{
    public static void main(String args[]){
        new Thread(new CountThread123()).start();
    }

    @Override
    public void run() {
        //To change body of generated methods, choose Tools | Templates.
        int x;
        try {
            for (x = 1; x < 11; x++) {
                System.out.print(x);
                System.out.print(" ");
                sleep(1000);
                if ((x % 5 == 0) && (x<10)) {
                    for (int y=1; y<=10;y++){
                        System.out.print("A");
                        System.out.print(" ");
                    }
                }
            }
            
            System.out.println();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by Jiayin328** [comment]
package twothreads;

public class TwoThreads extends Thread {
    
    int x=0;
     
    public static void main(String[] args) {
         new Thread(new TwoThreads()).start();
    }
    
    public void printA(int a){
        if (a==5){
            for (int y=0;y<10;y++){
                System.out.print("A");
            }
            System.out.print(" ");
        }
    }
    
    @Override
    public void run() {
        try {
            for (x = 0; x < 10; x++) {
                System.out.print((x+1) + " ");
                sleep(1000);
                printA(x+1);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by leejiawei95** [comment]
package twothreads;

public class TwoThreads extends Thread{

    public static void main(String[] args) {
        new Thread(new TwoThreads()).start();
    }

    public void run(){
        try{
            for (int a=1; a<=10; a++){
            System.out.print(a+" ");
            sleep(1000);
            
                if(a==5){
                    for(int b=1;b<11;b++){
                        System.out.print("A");
                    }
                System.out.print(" ");
                sleep(1000);
                }
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
}

**Comment by DonLeeHoi** [comment]
```
public  class Count2Thread extends Thread {`

public static void main(String[] args) {`
    new Thread(new Count2Thread()).start();`
     new Thread(new print()).start();`
 }


 @Override
 public void run() {
     try {
         for (int x = 1; x <= 10; x++) {
             System.out.println(x);
             if(x == 5){
             sleep(1000);
             System.out.println("");
             }
         }
     } catch (Exception e) {
         e.printStackTrace();
     }
 }
 
 
}

class print extends Thread{
	 @Override
	 public void run() {
	     
	     for (int x = 0; x <= 10; x++) {
	         System.out.print("A" + "  ");
	   }
	 }
}
```

**Comment by chinonn** [comment]
public class WeakTwo extends Thread {
		
		public static void main(String[] args) {
		    t1.start();
		 }

		static WeakTwo t1 = new WeakTwo(){
		    public void run(){
		        try{
		            for(int x=1; x<=10; x++){
		                System.out.print(" "+x+" ");
		                if(x==5){
		                    t2.start();
		                }
		                sleep(5000);
		            }
		        }catch(Exception e){
		            e.printStackTrace();
		        }
		    }
		};

		static WeakTwo t2 = new WeakTwo(){
		    public void run(){
		        try{
		            for(int i=0; i<10; i++)
		                System.out.print("A"); 
		            
		        }catch(Exception e){
		            e.printStackTrace();
		        }
		    }
		 };
		}

**Comment by TohWeiSheng** [comment]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twothreads;

/**
 *
 * @author User
 */
public class TwoThreads extends Thread {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        new Thread(new TwoThreads()).start();
    }

    @Override
     public void run() {
       try{
        for (int x = 1; x < 11; x++) {
            System.out.print(x + " "); 
             if (x==5){
                for(int i=0; i<10; i++)
                System.out.print("A" + ""); 
             }     
        }
}
  catch(Exception e){
   e.printStackTrace();
    }
}}

**Comment by LeongShyeLi** [comment]
package real.time_programming;

public class RunThread extends Thread {

    public static void main(String args[]) {
        t1.start();
    }

    static RunThread t1 = new RunThread() {
        @Override
        public void run() {
            try {
                for (int i = 1; i < 11; i++) {
                    System.out.print(i + " ");
                    if (i == 5) {
                        t2.start();
                    }
                    sleep(1000);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    };

    static RunThread t2 = new RunThread() {
        @Override
        public void run() {
            for (int x = 0; x < 10; x++) {
                System.out.print("A");
            }
            System.out.print(" ");
        }
    };
}

**Comment by Meenanbeega96** [comment]
public class ExerciseTwoThread extends Thread {

public static void main(String[] args) {

ExerciseTwoThread  t1 = new ExerciseTwoThread();
ExerciseTwoThread  t2 = new ExerciseTwoThread ();


try{
    for (int a=1; a<=10; a++) {
        System.out.print(a + " ");
        sleep(2000);
        
         if (a==5){
            for(int i=0; i<10; i++)
            System.out.print("A" + ""); 
             System.out.print(" ");
             
         }     
    }
}
catch(Exception e){
e.printStackTrace();
}
}

}

**Comment by Meenanbeega96** [comment]
public class ExerciseTwoThread extends Thread {

public static void main(String[] args) {

ExerciseTwoThread  t1 = new ExerciseTwoThread();
ExerciseTwoThread  t2 = new ExerciseTwoThread ();


try{
    for (int a=1; a<=10; a++) {
        System.out.print(a + " ");
        sleep(2000);
        
         if (a==5){
            for(int i=0; i<10; i++)
            System.out.print("A" + ""); 
             System.out.print(" ");
             
         }     
    }
}
catch(Exception e){
e.printStackTrace();
}
}

}

**Comment by Meenanbeega96** [comment]
public class ExerciseTwoThread extends Thread {

public static void main(String[] args) {

	ExerciseTwoThread  t1 = new ExerciseTwoThread();
	ExerciseTwoThread  t2 = new ExerciseTwoThread ();


	try{	
    	for (int a=1; a<=10; a++) {
        	System.out.print(a + " ");
        	sleep(2000);
        
         if (a==5){
         for(int i=0; i<10; i++)
           	 System.out.print("A" + ""); 
                 System.out.print(" ");
             
         }     
    }
}
catch(Exception e){
e.printStackTrace();
}
}

}

**Comment by Meenanbeega96** [comment]
public class ExerciseTwoThread extends Thread {

public static void main(String[] args) {

	ExerciseTwoThread  t1 = new ExerciseTwoThread();
	ExerciseTwoThread  t2 = new ExerciseTwoThread ();


	try{	
    	for (int a=1; a<=10; a++) {
            System.out.print(a + " ");
            sleep(2000);
        
         if (a==5){
        	 for(int i=0; i<10; i++)
                     System.out.print("A" + ""); 
                     System.out.print(" ");
             
           }     
       }
   }
	catch(Exception e){
	e.printStackTrace();
  }
 }

}

**Comment by Meenanbeega96** [comment]
public class ExerciseTwoThread extends Thread {

public static void main(String[] args) {

	ExerciseTwoThread  t1 = new ExerciseTwoThread();
	ExerciseTwoThread  t2 = new ExerciseTwoThread ();


	try{	
    	for (int a=1; a<=10; a++) {
            System.out.print(a + " ");
            sleep(2000);
        
         if (a==5){
        	 for(int i=0; i<10; i++)
                     System.out.print("A" + ""); 
                     System.out.print(" ");
                     sleep(2000);
           }     
       }
   }
	catch(Exception e){
	e.printStackTrace();
  }
 }

}

**Comment by khalilahfahmi** [comment]
package week2;

public class TwoThread extends Thread {

public static void main(String[] args) {
   
    TwoThread t1 = new TwoThread();
    TwoThread t2 = new TwoThread();
    
    try{
        for (int x = 1; x < 11; x++) {
            System.out.print(x + " "); 
            sleep(1000);
       
             if (x==5){
                for(int i=0; i<10; i++)
                System.out.print("A");
                System.out.print(" ");
                
             }
        }
    }
    
    catch(Exception e){
    e.printStackTrace();
    }
    
}
}

**Comment by munir95** [comment]
package javaapplication16;

import java.util.logging.Level;
import java.util.logging.Logger;


public class issue2 extends Thread {

   
    
    
    public static void main(String[] args) {
        
        
        Thread t1 = new Thread(new issue2() {
            public void run(){
                for (int x = 0; x < 11; x++){
                    System.out.println(x);
                    
                    if ( x == 5){
                        try {
                            sleep(20000);
                            System.out.println(x);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(issue2.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        
                        
                    }
                }
            }
        });
        
        Thread t2 = new Thread(new issue2(){
            public void run(){
                
               for (int x = 0; x < 10; x++){
                    System.out.println("A");    
               }
            }
        });
        t1.start();
        t2.start();
        
    }
    
    
    
}

**Comment by MarJr** [comment]
public class CountingThread2 extends Thread {

    public static void main(String[] args) {

        Thread t1 = new CountingThread2() {
            @Override
            public void run() {
                try {

                    for (int i = 0; i < 11; i++) {
                        if (i == 6) {
                            sleep(1000);
                        }
                        System.out.print(" " + i + " ");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        };
        Thread t2 = new PrintOut();

        t1.start();
        t2.start();
    }
}

class PrintOut extends Thread {

    @Override
    public void run() {
        for (int a = 0; a < 10; a++) {
            System.out.print("A");
        }
    }
}

**Comment by amirah16** [comment]
package twothread;

public class TwoThread extends Thread  {

    public static void main(String[] args) {
        
        TwoThread th1 = new TwoThread();
        TwoThread th2 = new TwoThread();

       try{
          for (int x = 1; x < 11; x++) {
           System.out.print(x + " "); 
          
  
         if (x==5){
            for(int j=1; j<11; j++)
            System.out.print("A");
            System.out.print(" ");
            
         }
    }
}
       catch(Exception e){
       e.printStackTrace();}
   
    }
}

**Comment by syeel** [comment]
```java
package twothreads;
public class TwoThreads{

    public static void main(String[] args) throws Exception {
        
        PrintNum pnum = new PrintNum();
        Thread pn1 = new Thread(pnum);
        pn1.start();
        
        PrintAlphab palb= new PrintAlphab();
        Thread pa1 = new Thread(palb);
        pa1.start();   
    } 
}
```

```java
package twothreads;
public class PrintNum implements Runnable{
    
    @Override
    public void run() {
        try {
            for (int x=1; x<=10; x++){
                System.out.print(x +" ");
                if (x==5){
                    Thread.sleep(100);
                }         
            }  
        }catch (Exception e){
            e.printStackTrace();
        }  
    }
}
```

```java
package twothreads;
public class PrintAlphab implements Runnable{

    @Override
    public void run() {
        for (int x=0; x<5; x++){
            System.out.print("A");
        }
        System.out.print(" ");
    }
```

**Comment by qianyinglum** [comment]
public class Count_Thread extends Thread {
    public static void main (String [] args){  
        t1.start();  
    }
    
    static Count_Thread t1 = new Count_Thread();
    int x;
    public void run(){
    
    
        try {
            
            for (x = 1; x<11; x++){
            System.out.print(x+" ");
            sleep(500);
   
         Count_Thread t2 = new Count_Thread();
         char i = 'A';
            if(x==5&&x<10)
                
                for (i = 1; i<11;i++){
                System.out.print("A");
                }
            System.out.print(" ");
        }
            
            
   }catch (Exception e){
    e.printStackTrace();
    
        }
    } 
}

**Comment by zhamri** [comment]
Closed.
